[tox]
requires =
    tox>=4
    tox-uv>=1
# Use
#   uv python list --managed-python to see what is available from via tox-uv
# It does not seem possible to have `envlist` auto-updated w/o parsing the
# output of the above command, so it must be manually updated.
envlist = py38,py39,py310,py311,py312,py313,py314
skip_missing_interpreters = false

# Default test environment. Use `tox` or, e.g., `tox -e py38` to run these tests.
[testenv]
runner = uv-venv-runner
deps =
    pytest
    deepdiff
commands =
  pytest -s -v -m 'not long' {posargs}

# Use `tox -e long-test` to run `long` tests.
[testenv:long-test]
runner = uv-venv-runner
deps =
    pytest
    deepdiff
commands =
  python -m pytest -v -m 'long' hapiclient/test/test_hapi.py

